# Site settings
title: mfp20 - minority-reported only
url: "http://mfp20.github.io"
timezone: CET
future: true

# Build settings
# markdown: redcarpet
markdown: kramdown
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "fenced_code_blocks"]
